import Foundation
import SwiftData

/// A line on the shopping list for a given week. Generated by rolling up the
/// week's planned meals, but hand-added items survive regeneration.
@Model
final class GroceryItem {
    var name: String = ""
    var quantity: Double = 0
    var unit: String = ""
    var aisle: String = GroceryAisle.other.rawValue
    var isChecked: Bool = false
    /// Start-of-week this line belongs to, so old lists stay browsable.
    var weekStart: Date = Date.now
    /// True when a person typed it in, which protects it from regeneration.
    var isManual: Bool = false
    /// Reminders identifier once exported, to avoid duplicate reminders.
    var reminderID: String?
    var createdAt: Date = Date.now

    init(
        name: String = "",
        quantity: Double = 0,
        unit: String = "",
        aisle: GroceryAisle = .other,
        weekStart: Date = .now,
        isManual: Bool = false
    ) {
        self.name = name
        self.quantity = quantity
        self.unit = unit
        self.aisle = aisle.rawValue
        self.weekStart = Calendar.current.startOfWeek(for: weekStart)
        self.isManual = isManual
        self.createdAt = .now
    }

    var aisleValue: GroceryAisle {
        get { GroceryAisle(rawValue: aisle) ?? .other }
        set { aisle = newValue.rawValue }
    }

    var displayText: String {
        var parts: [String] = []
        if quantity > 0 { parts.append(Ingredient.format(quantity)) }
        if !unit.isEmpty { parts.append(unit) }
        parts.append(name)
        return parts.joined(separator: " ")
    }
}
