import Foundation
import SwiftData

/// A line on the shopping list for a given week. Generated by rolling up the
/// week's planned meals, but hand-added items survive regeneration.
@Model
final class GroceryItem {
    var name: String = ""
    var quantity: Double = 0
    var unit: String = ""
    var aisle: String = GroceryAisle.other.rawValue
    var isChecked: Bool = false
    /// Start-of-week this line belongs to, so old lists stay browsable.
    var weekStart: Date = Date.now
    /// True when a person typed it in, which protects it from regeneration.
    var isManual: Bool = false
    /// Struck off by hand. Auto lines are rebuilt from the plan every time the
    /// sheet opens, so a swipe has to be remembered or the item walks back in.
    var isDismissed: Bool = false
    /// Title of the recipe this line came from, for the origin suffix.
    var originTitle: String = ""
    /// Reminders identifier once exported, to avoid duplicate reminders.
    var reminderID: String?
    var createdAt: Date = Date.now
    var sourcesData: Data?
    var purchasesData: Data?

    var sources: [GrocerySource] {
        get { sourcesData.flatMap { try? JSONDecoder().decode([GrocerySource].self, from: $0) } ?? [] }
        set { sourcesData = try? JSONEncoder().encode(newValue) }
    }
    var purchases: [String: Double] {
        get { purchasesData.flatMap { try? JSONDecoder().decode([String: Double].self, from: $0) } ?? [:] }
        set { purchasesData = try? JSONEncoder().encode(newValue) }
    }
    func outstanding(for selected: Set<String>? = nil) -> Double {
        sources.filter { selected == nil || selected!.contains($0.id) }.reduce(0) {
            $0 + max(0, $1.quantity - (purchases[$1.id] ?? 0))
        }
    }
    func isPurchased(for selected: Set<String>? = nil) -> Bool {
        let relevant = sources.filter { selected == nil || selected!.contains($0.id) }
        guard !relevant.isEmpty else { return isChecked }
        return relevant.allSatisfy { (purchases[$0.id] ?? -1) + 0.000001 >= $0.quantity }
    }
    func setPurchased(_ checked: Bool, for selected: Set<String>? = nil) {
        var saved = purchases
        for source in sources where selected == nil || selected!.contains(source.id) {
            if checked { saved[source.id] = source.quantity } else { saved.removeValue(forKey: source.id) }
        }
        purchases = saved
        isChecked = sources.isEmpty ? checked : isPurchased()
    }

    init(
        name: String = "",
        quantity: Double = 0,
        unit: String = "",
        aisle: GroceryAisle = .other,
        weekStart: Date = .now,
        isManual: Bool = false
    ) {
        self.name = name
        self.quantity = quantity
        self.unit = unit
        self.aisle = aisle.rawValue
        // The window key is whatever the builder says it is — the rolling
        // 7-night window starts on an arbitrary day, not the calendar week.
        self.weekStart = Calendar.current.startOfDay(for: weekStart)
        self.isManual = isManual
        self.createdAt = .now
    }

    var aisleValue: GroceryAisle {
        get { GroceryAisle(rawValue: aisle) ?? .other }
        set { aisle = newValue.rawValue }
    }

    var displayText: String {
        [GroceryMeasure.shopping(quantity, unit).text, name].filter { !$0.isEmpty }.joined(separator: " ")
    }
}
